#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

try {
    $status = (require_once __DIR__.'/bootstrap/app.php')
        ->handleCommand(new ArgvInput);
    exit($status);
} catch (Throwable $e) {
    echo "ARTISAN ROOT ERROR: " . get_class($e) . ": " . $e->getMessage() . "\n";
    echo "In " . $e->getFile() . ":" . $e->getLine() . "\n";
    echo $e->getTraceAsString() . "\n";
    exit(1);
}

